### ISSUE TITLE
Parry & Toughness

### ISSUE THREAD

**Issue by paladintodd** [mrcomac/token-action-hud-swade#34]
Would be nice to have a "Defense" item that showed Parry and Toughness. Even nicer if it gave the full breakdown like the character sheet does.

**Comment by steveculshaw** [comment]
You could maybe use other modules to show it, e.g. Bar Brawl ?

**Comment by paladintodd** [comment]
Yeah, Bar Brawl works for what I want.

**Comment by mrcomac** [comment]
Thank you, @steveculshaw. I'm hesitant to transform the HUD into a sheet where you can see those stats. The HUD is intended to be a shortcut for actions (Token Action HUD) rather than for displaying stats/info.

Maybe I'm wrong and we should have those info in the HUD.

There's always the possibility to add a configuration option for how the HUD behaves (display everything from the sheet or only the possible actions?).

btw, I'm working to make the Argo token hud compatible with savage worlds, that hud indeed will have that information.

**Comment by paladintodd** [comment]
I mean, it's all optional right? If you want only actions you can leave out
those items. If you want it, add them in

**Comment by mrcomac** [comment]
This request pertains to the addition of non-actionable items to the HUD. I am closing it in favor of proceeding with task https://github.com/mrcomac/token-action-hud-swade/issues/35
