### ISSUE TITLE
Rolls not working with BR2

### ISSUE THREAD

**Issue by Gorka-de-Ituroitz** [mrcomac/token-action-hud-swade#36]
An error occurs when trying to make a roll from the Token HUD when BR2 is selected in the config, and the roll card does not appear in the chat.
![image](https://github.com/mrcomac/token-action-hud-swade/assets/137724382/96e0d86f-d666-4ac6-80d5-2edead146bd3)

- Token Action HUD Core: 1.5.3
- Token Action HUD SWADE: 0.9.5
- Swade System: 3.3.6
- Foundry VTT: 11.315
- Browser: Opera One (ver.: 108.0.5067.29) | Chromium version:122.0.6261.112

**Comment by r2roberts** [comment]
I'm seeing this also.

**Comment by r2roberts** [comment]
On Discord TheCemist said...

TheChemist — 03/18/2024 5:38 PM
Ah, interesting. Yeah, we changed the way that settings are managed so that things are better organized. If an external module was depending on one of those settings, that's not going to work anymore. You can tell them to reach out to me and I can help them sort things out.

**Comment by r2roberts** [comment]
Thanks!

**Comment by Gorka-de-Ituroitz** [comment]
Great. Thank you!
