### ISSUE TITLE
Reset Actions not working

### ISSUE THREAD

**Issue by Vogliadicone** [mrcomac/token-action-hud-swade#8]
After deleting a category in the Token Action HUD I can't get the category back. F.e. I deleted the category "General". I thought, the "Reset Actions" button would bring the category back, but that wasn't the case. The category was still missing after that.
![ResetActions](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/7a7e4fac-6f0c-4923-b285-8cdca1e50ccb)

Also just typing "General" into the field with the groups creates a new group "General", but without the standard content, i.e. the Bennies.

I could only bring back the "General" category via the "Reset HUD" option in the module options and an reload. But after doing so, I had to reconfigure the HUD for all my players. So an easier way would be appreciated.

- Token Action HUD Core: 1.4.9
- Token Action HUD SWADE: 0.6.1
- Swade System: 3.0.4
- Foundry VTT: 11.302
- Browser: Google Chrome

**Comment by mrcomac** [comment]
This update might resolve this issue
https://github.com/Larkinabout/fvtt-token-action-hud-core/releases/tag/1.4.10

**Comment by Larkinabout** [comment]
There's an important difference between the 'Reset Actions' operation and the 'Reset HUD' module setting to be aware of.
- **Reset Actions** resets the actions within groups for the selected actor only. So, if you remove an action that is added by default it will be re-added.
- **Reset HUD** resets the groups for the user back to the default layout. So, if you delete a group that is added by default it will be re-added.

This is because the layout of actions (their order and whether they are shown or hidden) is stored per actor, but the layout of groups is stored per user.

If the case of this issue, you'd want to use the 'Reset HUD' module setting for Token Action HUD Core.

**Comment by Vogliadicone** [comment]
Like I said in my first post, the "Reset HUD" button in the module setting for Token Action HUD Core works.

What's not working for me is the "Reset Actions" button has no effect. F.e. I delete all categories under "Skills", press "Reset Actions" and there are still no catehories under "Skills". The "Reset Action" button seems to have no effect at all.

If you can't reproduce it, can I help you with some data? What do you need?

- Token Action HUD Core: 1.4.11
- Token Action HUD SWADE: 0.7.0
- Swade System: 3.0.4
- Foundry VTT: 11.304
- Browser: Google Chrome

**Comment by Vogliadicone** [comment]
Just to let you know, I updated to 0.7.2, reseted the Token Action HUD via the "Reset HUD" option and still have the same problem.

F.e. I added some stuff to the "General" section:
![HUD_1](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/184dbf7d-b894-4882-a183-9df0ebcb7652)
And didn't see any changes after "Reset Actions":
![HUD_2](https://github.com/mrcomac/token-action-hud-swade/assets/119852651/0b254a13-46ee-4e22-93e8-cc9b38daa997)

Not a big deal, since the "Reset HUD" button is working, but after using that, I have to reconfigure the HUD settings for all my players.

**Comment by mrcomac** [comment]
I'll test the behavior of this on DND using the action token hud for dnd and will replicate to swade.

**Comment by mrcomac** [comment]
same behaviour on the DND HUD.. I'll keep investigating.

**Comment by Larkinabout** [comment]
Just to clarify the 'Reset Actions' operation resets actions within groups, it doesn't reset the groups themselves. Once you start editing the HUD, there's no halfway reset, you either need to start over or just delete the groups that you previously added but don't want anymore.

**Comment by mrcomac** [comment]
@Larkinabout when we click on reset actions, is it possible to HUD  core remove action for that group and call a function in action handle passing the group to reset the actions? This way we can add a feature to the sysstem huds to reset a specific group (hud core removes and each other hud needs to rebuild it)

It's a change that requires all other huds to change to write the _reloadActions function.  Maybe can also allow to setup a config variable to true or false and disable this behavior to keep compatibility with is already in place, and if a hud wants to implement it, also need to change this variable to true.

**Comment by Larkinabout** [comment]
> Hm, I fear, I still don't get it or it doesn't work like expected. Per default the group "Attributes" shows "Attributes" and "Derived Stats". I delete the "Derived Stats" within that group. Later I press the "Reset Actions" button.

Hopefully this illustrates what 'Reset Actions' does:

![token-action-hud-core-reset-actions](https://github.com/mrcomac/token-action-hud-swade/assets/105953297/236082fe-d22c-4547-af84-c7b4a8033793)

It resets the actions within groups, it doesn't add/remove groups or restore the HUD to the default layout.

I've chosen not to add a 'Reset Groups' operation as they are easy to add or remove and for the whole HUD, the 'Reset HUD' can be used. In the future, I may extend it so that there's a reset actions operation per group, but resetting individual groups is better done by removing or adding them.

> @Larkinabout when we click on reset actions, is it possible to HUD core remove action for that group and call a function in action handle passing the group to reset the actions? This way we can add a feature to the sysstem huds to reset a specific group (hud core removes and each other hud needs to rebuild it)

As a core operation I think it'd end up confusing users if the button does a different thing for different systems.

If I can understand what function you're trying to achieve, it may be it can be added as a core feature.

**Comment by mrcomac** [comment]
@Vogliadicone since the misunderstanding has been solved can we close this issue?

**Comment by Vogliadicone** [comment]
Sure.
